---
# Bash configuration for root
- name: Copy full bashrc for root
  copy:
    src: root_block
    dest: /root/.bashrc
    owner: root
    group: root
    mode: '0644'

- name: Load mate terminal settings for root
  shell: dconf load /org/mate/terminal/ < mate-terminal-settings_root.dconf
  args:
    chdir: "{{ role_path }}/files"

# Bash configuration for user
- name: Copy full bashrc for user
  copy:
    src: bashrc_user_block
    dest: "{{ home_dir }}/.bashrc"
    owner: "{{ regular_user }}"
    group: "{{ regular_user }}"
    mode: '0644'

- name: Load mate terminal settings for user
  become_user: "{{ regular_user }}"
  shell: dconf load /org/mate/terminal/ < mate-terminal-settings_user.dconf
  args:
    chdir: "{{ role_path }}/files" 