---
# Install Firefox latest
- name: Download Firefox
  get_url:
    url: "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US"
    dest: "/tmp/firefox.tar.bz2"

- name: Extract Firefox
  unarchive:
    src: "/tmp/firefox.tar.bz2"
    dest: "/opt"
    remote_src: yes

- name: Create Firefox desktop entry
  copy:
    content: |
      [Desktop Entry]
      Name=Firefox
      Comment=Browse the World Wide Web
      GenericName=Web Browser
      X-GNOME-FullName=Firefox Web Browser
      Exec=/opt/firefox/firefox %u
      Terminal=false
      X-MultipleArgs=false
      Type=Application
      Icon=/opt/firefox/browser/chrome/icons/default/default128.png
      Categories=Network;WebBrowser;
      MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/vnd.mozilla.xul+xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;
      StartupNotify=true
    dest: /usr/share/applications/firefox.desktop
    mode: '0644' 