---
- name: "Copy User .bashrc"
  copy:
    src: "{{ role_path }}/files/user.bashrc"
    dest: "{{ ansible_env.HOME }}/.bashrc"

- name: "Copy Root .bashrc"
  copy:
    src: "{{ role_path }}/files/root.bashrc"
    dest: "/root/.bashrc"

- name: "Read current mate terminal profiles"
  dconf:
    key: "/org/mate/terminal/global/profile-list"
    state: "read"
  register: "profile_list"

- name: "profile_list was not set, setting"
  set_fact:
    profile_list:
      value: '["default"]'
  when: profile_list.value is none
