---
# All apt-related tasks from claude.yml
- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
    become: true
    become_method: sudo

- name: Upgrade all packages
  apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes
    become: true
    become_method: sudo

- name: Install basic packages
  apt:
    name:
      - curl
      - ca-certificates
      - wget
      - git
      - unzip
      - ftp
      - jq
      - exiftool
      - terminator
      - redshift
      - code
      - exploitdb
      - snmp
      - tftp
      - freerdp2-x11
      - steghide
      - pipx
    state: present
    become: true
    become_method: sudo

- name: Remove codium
  apt:
    name: codium
    state: absent
    become: true
    become_method: sudo

- name: "Remove unofficial docker images"
  package:
    name: 
      - docker.io
      - docker-compose
      - docker-doc
      - podman-docker
    state: absent
  register: docker_remove  
  become: true
  become_method: sudo

- name: "Remove NetExec - We want to use pipx for this"
  package:
    name: 
      - netexec
    state: absent
  become: true
  become_method: sudo

- name: "Remove Containerd/Runc"
  package:
    name: 
      - containerd
      - runc
    state: absent
  when: docker_remove.changed
  become: true
  become_method: sudo

  - name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo
---

